In [1]:
import theano
from theano import tensor as T, function

import numpy as np

WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.


In [9]:
X = T.matrix('x')
Y = X ** 2
Z = T.grad(Y.sum(), X)
F = function([X], [Y, Z])

In [10]:
x = np.ones((2, 2)) * 3
y, z = F(x)

print(x)
print(y)
print(z)

[[3. 3.]
 [3. 3.]]
[[9. 9.]
 [9. 9.]]
[[6. 6.]
 [6. 6.]]
